<!doctype html>
<html lang="en"><head><meta charset="utf-8">@include('partials.site-theme')<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>Community feedback · Any2Convert</title>@include('partials.tailwind-assets')
<style>:root{--ink:#252923;--muted:#747b72;--line:#e7eae4;--paper:#fff;--wash:#f6f7f4;--green:#315b3d;--soft:#edf4eb}html.dark{--ink:#edf0e9;--muted:#a3ab9e;--line:#343b33;--paper:#1b201b;--wash:#111511;--green:#9cc5a0;--soft:#202b21;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:var(--wash);color:var(--ink);font:15px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{width:min(900px,calc(100% - 32px));margin:36px auto 64px}.head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:22px}.eyebrow{margin:0;color:var(--green);font-size:11px;font-weight:750;letter-spacing:.13em;text-transform:uppercase}h1{margin:5px 0;font-size:clamp(28px,4vw,38px);letter-spacing:-.045em;line-height:1.1}.muted{color:var(--muted);font-size:13px}.card{margin:13px 0;padding:20px;border:1px solid var(--line);border-radius:14px;background:var(--paper);box-shadow:0 6px 24px #28362606}.card h2{margin:0;font-size:18px;letter-spacing:-.025em}.meta{margin-top:5px;color:var(--muted);font-size:12px}.body{margin:12px 0 0;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--ink)}.button{display:inline-flex;align-items:center;justify-content:center;min-height:39px;padding:0 13px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink);font:inherit;font-size:13px;font-weight:700;text-decoration:none;cursor:pointer}.primary{background:var(--green);border-color:var(--green);color:white}.danger{color:#a23d32}.control{width:100%;padding:10px 11px;margin-top:6px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink);font:inherit}.notice{padding:11px 13px;background:var(--soft);border:1px solid var(--line);border-radius:9px;color:var(--green);margin-bottom:14px}.post-form{display:grid;gap:12px}.post-form label{font-size:12px;font-weight:700}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.tag{display:inline-block;border-radius:99px;background:var(--soft);padding:3px 9px;color:var(--green);font-size:11px;font-weight:700}.empty{text-align:center;padding:35px 15px}.pagination{margin-top:18px}.tools{display:flex;justify-content:space-between;gap:12px;align-items:center}@media(max-width:560px){.wrap{width:calc(100% - 24px);margin-top:24px}.head{align-items:flex-start;flex-direction:column}.card{padding:16px}}</style></head>
<body>@include('partials.site-navbar')<main class="wrap">
    <header class="head"><div><p class="eyebrow">Ideas, questions and shared help</p><h1>Community feedback</h1><p class="muted" style="margin:7px 0 0">Share suggestions, compare notes, and help each other get the most from Any2Convert.</p></div><a class="button" href="{{ route('contact.show', ['category' => 'feedback']) }}">Private support</a></header>
    @if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
    @if(!$available)
        <section class="card"><h2>Community is being set up</h2><p class="muted">The community database tables have not been installed yet. Please check back soon.</p></section>
    @else
    @auth
        @if(auth()->user()->is_restricted && !auth()->user()->isAdmin())<section class="card muted">Posting and replying are restricted for this account. You can still read the community.</section>@else<section class="card"><h2>Start a conversation</h2><p class="muted" style="margin:4px 0 14px">Posts are public. Please don’t share private account details or sensitive files.</p><form class="post-form" method="post" action="{{ route('community.store') }}">@csrf<label>Title<input class="control" name="title" value="{{ old('title') }}" maxlength="180" minlength="5" required></label>@error('title')<span class="muted">{{ $message }}</span>@enderror<label>Your post<textarea class="control" name="body" rows="4" maxlength="12000" minlength="10" required>{{ old('body') }}</textarea></label>@error('body')<span class="muted">{{ $message }}</span>@enderror<button class="button primary" type="submit">Post to community</button></form></section>@endif
    @else
        <section class="card tools"><span class="muted">Sign in to post and join a conversation.</span><a class="button primary" href="{{ route('login', ['redirect' => request()->fullUrl()]) }}">Sign in</a></section>
    @endauth
    @forelse($posts as $post)
        <article class="card"><div class="tools"><div><h2><a href="{{ route('community.show', $post) }}" style="color:inherit;text-decoration:none">{{ $post->title }}</a></h2><div class="meta">{{ $post->author?->name ?? 'Community member' }} · {{ $post->created_at?->format('M j, Y') }} · {{ $post->comments_count }} {{ \Illuminate\Support\Str::plural('reply', $post->comments_count) }}</div></div>@if($post->status !== 'published')<span class="tag">Hidden</span>@endif</div><p class="body">{{ \Illuminate\Support\Str::limit($post->body, 360) }}</p><div class="actions"><a class="button" href="{{ route('community.show', $post) }}">Open conversation</a>
            @if(auth()->check() && (auth()->user()->isAdmin() || (int)$post->user_id === (int)auth()->id()))<details><summary class="button">Edit</summary><form class="post-form" method="post" action="{{ route('community.update', $post) }}" style="margin-top:9px">@csrf @method('PATCH')<label>Title<input class="control" name="title" value="{{ $post->title }}" maxlength="180" required></label><label>Post<textarea class="control" name="body" rows="4" maxlength="12000" required>{{ $post->body }}</textarea></label><button class="button primary">Save changes</button></form></details><form method="post" action="{{ route('community.delete', $post) }}" onsubmit="return confirm('Delete this post and all replies?')">@csrf @method('DELETE')<button class="button danger">Delete</button></form>@endif
            @if(auth()->check() && auth()->user()->isAdmin())<form method="post" action="{{ route('admin.community.moderate', $post) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $post->status === 'published' ? 'hidden' : 'published' }}"><button class="button">{{ $post->status === 'published' ? 'Hide' : 'Publish' }}</button></form>@endif
        </div></article>
    @empty
        <section class="card empty"><h2>No conversations yet</h2><p class="muted">Start the first discussion and help shape the tools.</p></section>
    @endforelse
    @if($posts->hasPages())<div class="pagination">{{ $posts->links() }}</div>@endif
    @endif
</main>@include('partials.site-footer')</body></html>
