<!doctype html>
<html lang="en"><head><meta charset="utf-8">@include('partials.site-theme')<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>{{ $post->title }} · Community · Any2Convert</title>@include('partials.tailwind-assets')
<style>:root{--ink:#252923;--muted:#747b72;--line:#e7eae4;--paper:#fff;--wash:#f6f7f4;--green:#315b3d;--soft:#edf4eb}html.dark{--ink:#edf0e9;--muted:#a3ab9e;--line:#343b33;--paper:#1b201b;--wash:#111511;--green:#9cc5a0;--soft:#202b21;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:var(--wash);color:var(--ink);font:15px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{width:min(850px,calc(100% - 32px));margin:34px auto 64px}.back{display:inline-block;margin-bottom:15px;color:var(--green);font-size:13px;font-weight:700;text-decoration:none}.card{padding:21px;border:1px solid var(--line);border-radius:14px;background:var(--paper);box-shadow:0 6px 24px #28362606}.post{margin-bottom:20px}.post h1{margin:5px 0;font-size:clamp(26px,4vw,36px);line-height:1.15;letter-spacing:-.04em;overflow-wrap:anywhere}.eyebrow{margin:0;color:var(--green);font-size:11px;font-weight:750;letter-spacing:.13em;text-transform:uppercase}.muted{color:var(--muted);font-size:13px}.body{margin:16px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.button{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:0 12px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink);font:inherit;font-size:12px;font-weight:700;text-decoration:none;cursor:pointer}.primary{background:var(--green);border-color:var(--green);color:white}.danger{color:#a23d32}.control{width:100%;padding:10px;margin-top:6px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink);font:inherit}.reply{padding:17px 0;border-top:1px solid var(--line)}.reply:first-child{border-top:0}.reply-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.reply-author{font-size:13px;font-weight:750}.admin-tag{margin-left:6px;padding:2px 6px;border-radius:99px;background:var(--soft);color:var(--green);font-size:10px}.notice{padding:11px 13px;background:var(--soft);border:1px solid var(--line);border-radius:9px;color:var(--green);margin-bottom:14px}.reply-form{display:grid;gap:10px}.empty{padding:20px 0;text-align:center}@media(max-width:560px){.wrap{width:calc(100% - 24px);margin-top:23px}.card{padding:16px}}</style></head>
<body>@include('partials.site-navbar')<main class="wrap"><a class="back" href="{{ route('community.index') }}">← Community feedback</a>
    @if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
    <article class="card post"><p class="eyebrow">Community conversation @if($post->status !== 'published')· Hidden @endif</p><h1>{{ $post->title }}</h1><div class="muted">{{ $post->author?->name ?? 'Community member' }} · {{ $post->created_at?->format('M j, Y · g:i a') }}</div><p class="body">{{ $post->body }}</p>
        @if(auth()->check() && (auth()->user()->isAdmin() || (int)$post->user_id === (int)auth()->id()))
            <div class="actions"><details><summary class="button">Edit post</summary><form method="post" action="{{ route('community.update', $post) }}" style="margin-top:8px">@csrf @method('PATCH')<label class="muted">Title<input class="control" name="title" value="{{ $post->title }}" maxlength="180" required></label><label class="muted" style="display:block;margin-top:9px">Post<textarea class="control" name="body" rows="5" maxlength="12000" required>{{ $post->body }}</textarea></label><button class="button primary" style="margin-top:9px">Save changes</button></form></details><form method="post" action="{{ route('community.delete', $post) }}" onsubmit="return confirm('Delete this post and all replies?')">@csrf @method('DELETE')<button class="button danger">Delete post</button></form></div>
        @endif
        <a class="button" style="margin-top:9px" href="{{ route('contact.show', ['category' => 'feedback', 'subject' => 'Report community post #'.$post->id]) }}">Report this post</a>
        @if(auth()->check() && auth()->user()->isAdmin())<form method="post" action="{{ route('admin.community.moderate', $post) }}" style="margin-top:9px">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $post->status === 'published' ? 'hidden' : 'published' }}"><button class="button">{{ $post->status === 'published' ? 'Hide from community' : 'Publish post' }}</button></form>@endif
    </article>

    <section class="card"><h2 style="margin:0 0 12px">Replies ({{ $post->comments->count() }})</h2>
        @forelse($post->comments as $comment)
            <article class="reply"><div class="reply-head"><div class="reply-author">{{ $comment->author?->name ?? 'Community member' }} @if($comment->author?->isAdmin())<span class="admin-tag">Admin</span>@endif</div><time class="muted">{{ $comment->created_at?->format('M j, Y · g:i a') }}</time></div><p class="body">{{ $comment->body }}</p>
                @if(auth()->check() && (auth()->user()->isAdmin() || (int)$comment->user_id === (int)auth()->id()))
                    <div class="actions"><details><summary class="button">Edit reply</summary><form method="post" action="{{ route('community.comment.update', [$post, $comment]) }}" style="margin-top:8px">@csrf @method('PATCH')<textarea class="control" name="body" rows="3" maxlength="8000" required>{{ $comment->body }}</textarea><button class="button primary" style="margin-top:7px">Save edit</button></form></details><form method="post" action="{{ route('community.comment.delete', [$post, $comment]) }}" onsubmit="return confirm('Delete this reply?')">@csrf @method('DELETE')<button class="button danger">Delete reply</button></form></div>
                @endif
                <a class="button" style="margin-top:8px" href="{{ route('contact.show', ['category' => 'feedback', 'subject' => 'Report community reply #'.$comment->id]) }}">Report reply</a>
            </article>
        @empty
            <p class="muted empty">No replies yet. Add the first helpful response.</p>
        @endforelse
        @auth
            @if(($post->status === 'published' || auth()->user()->isAdmin()) && (!auth()->user()->is_restricted || auth()->user()->isAdmin()))<form class="reply-form" method="post" action="{{ route('community.comment', $post) }}" style="margin-top:14px;padding-top:15px;border-top:1px solid var(--line)">@csrf<label class="muted" for="communityReply" style="font-weight:700">Join the conversation</label><textarea class="control" id="communityReply" name="body" rows="4" maxlength="8000" required>{{ old('body') }}</textarea>@error('body')<span class="muted">{{ $message }}</span>@enderror<button class="button primary" type="submit" style="justify-self:start">Post reply</button></form>@elseif(auth()->user()->is_restricted && !auth()->user()->isAdmin())<p class="muted">Posting and replying are restricted for this account.</p>@endif
        @else
            <p class="muted" style="margin-top:16px"><a href="{{ route('login') }}">Sign in</a> to reply.</p>
        @endauth
    </section>
</main>@include('partials.site-footer')</body></html>
